# This workflow will update release version number after pull request merge on main branch
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update release version number

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  id-token: write
  contents: write

jobs:
  increase_major_release_version_number:
    if: github.event.pull_request.merged == true && github.ref_type == 'branch' && (contains(github.ref_name, 'major/') || contains(github.ref_name, 'release/'))

    name: Update major release version number
    runs-on: [ubuntu-latest]

    steps:
      - name: actions/checkout@v3
        uses: actions/checkout@v3

      - name: actions/setup-node@v3 with node-version latest
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Set user name and user email for github actions
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: $ git status
        run: git status

      - name: Increase major release version number
        run: npm run release-version:major

      - name: $ git status
        run: git status

      - name: $ git add .
        run: git add .

      - name: $ git status
        run: git status

      - name: $ git commit
        run: git commit --amend --no-edit

      - name: $ git status
        run: git status

      - name: $ git push --force
        run: git push --force

      - name: $ git status
        run: git status

  increase_minor_release_version_number:
    if: github.event.pull_request.merged == true && github.ref_type == 'branch' && contains(github.ref_name, 'feature/')

    name: Update minor release version number
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [16.16.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set user name and user email for github actions
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: $ git status
        run: git status

      - name: Increase minor release version number
        run: npm run release-version:minor

      - name: $ git status
        run: git status

      - name: $ git add .
        run: git add .

      - name: $ git status
        run: git status

      - name: $ git commit
        run: git commit --amend --no-edit

      - name: $ git status
        run: git status

      - name: $ git push --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push --force

      - name: $ git status
        run: git status

  increase_patch_release_version_number:
    if: github.event.pull_request.merged == true && github.ref_type == 'branch' && (contains(github.ref_name, 'fix/') || contains(github.ref_name, 'patch/'))

    name: Update patch release version number
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [16.16.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set user name and user email for github actions
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: $ git status
        run: git status

      - name: Increase patch release version number
        run: npm run release-version:patch

      - name: $ git status
        run: git status

      - name: $ git add .
        run: git add .

      - name: $ git status
        run: git status

      - name: $ git commit
        run: git commit --amend --no-edit

      - name: $ git status
        run: git status

      - name: $ git push --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push --force

      - name: $ git status
        run: git status
